language: python

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
      install:
        - pip install zigate[dev] homeassistant>=0.110
      script:
        - tox
        - python3 -m unittest
    - python: 3.8
      env: TOXENV=py38
      install:
        - pip install zigate[dev] homeassistant>=0.110
      script:
        - tox
        - python3 -m unittest
